name: hsk-llvm
version: 0.1.0.0
github: "hhoikoo00/hsk-llvm"
license: BSD3
author: "Hyunhoi Koo"
maintainer: "hhoikoo00@gmail.com"
copyright: "2021 Hyunhoi Koo"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/hhoikoo00/hsk-llvm#readme>

dependencies:
  - base
  - containers
  - text
  - megaparsec
  - parser-combinators
  - hspec
  - hspec-megaparsec

library:
  source-dirs: src

executables:
  hsk-llvm-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsk-llvm

tests:
  hsk-llvm-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsk-llvm
